---
deployment:
  tasks:
    - cd /home/primary/public_html/cal.sitepact.com
    - export NODE_OPTIONS="--max-old-space-size=2048"
    - set -a; [ -f ".env.cpanel" ] && . ".env.cpanel"; set +a
    - /opt/cpanel/ea-nodejs22/bin/node -v
    - /opt/cpanel/ea-nodejs22/bin/corepack enable
    - /opt/cpanel/ea-nodejs22/bin/corepack prepare yarn@stable --activate
    - /opt/cpanel/ea-nodejs22/bin/yarn install --immutable
    - /opt/cpanel/ea-nodejs22/bin/yarn workspace @calcom/prisma db-deploy
    - /opt/cpanel/ea-nodejs22/bin/yarn build
    - mkdir -p tmp
    - touch tmp/restart.txt
