---
deployment:
  tasks:
    - cd /home/primary/public_html/cal.sitepact.com

    # Extra heap for build
    - export NODE_OPTIONS="--max-old-space-size=2048"

    # Load build-time env (kept OFF-GIT)
    - set -a; [ -f ".env.cpanel" ] && . ".env.cpanel"; set +a

    # Install deps from yarn.lock (Yarn v1 uses node_modules/)
    - /opt/cpanel/ea-nodejs22/bin/yarn install --frozen-lockfile

    # Prisma migrations (workspace script first, fallback to CLI)
    - /opt/cpanel/ea-nodejs22/bin/yarn workspace @calcom/prisma db-deploy \
        || /opt/cpanel/ea-nodejs22/bin/npx prisma migrate deploy

    # Build
    - /opt/cpanel/ea-nodejs22/bin/yarn build

    # Restart Passenger
    - mkdir -p tmp
    - touch tmp/restart.txt
