---
deployment:
  tasks:
    - cd /home/primary/public_html/cal.sitepact.com

    # More RAM for install/build
    - export NODE_OPTIONS="--max-old-space-size=4096"

    # Load build-time env (keep .env.cpanel OFF-GIT)
    - set -a; [ -f ".env.cpanel" ] && . ".env.cpanel"; set +a

    # Install deps with vendored Yarn (uses node_modules via .yarnrc.yml)
    - node .yarn/releases/yarn-3.4.1.cjs install --immutable --inline-builds

    # Prisma migrations (workspace script first; fallback to CLI)
    - node .yarn/releases/yarn-3.4.1.cjs workspace @calcom/prisma db-deploy \
        || npx prisma migrate deploy

    # Build
    - node .yarn/releases/yarn-3.4.1.cjs build

    # Restart Passenger
    - mkdir -p tmp && touch tmp/restart.txt
